const express    = require('express')
const router     = express.Router()
const auth       = require('../middleware/auth')
const aiCtrl     = require('../controllers/aiController')

router.post('/chatbot',       auth, aiCtrl.chatbot)
router.post('/summarize',     auth, aiCtrl.summarize)
router.post('/notes',         auth, aiCtrl.generateNotes)
router.post('/flashcards',    auth, aiCtrl.generateFlashcards)
router.post('/questions',     auth, aiCtrl.generateQuestions)
router.post('/timetable',     auth, aiCtrl.generateTimetable)
router.post('/career-guidance',auth, aiCtrl.careerGuidance)
router.post('/career-roadmap', auth, aiCtrl.careerRoadmap)
router.post('/skill-gap',      auth, aiCtrl.skillGap)
router.post('/resume',         auth, aiCtrl.buildResume)
router.post('/mock-interview', auth, aiCtrl.mockInterview)
router.post('/wellbeing',      auth, aiCtrl.wellbeing)
router.post('/image-doubt',    auth, aiCtrl.imageDoubt)

module.exports = router