import { useEffect, useRef, useState } from 'react'
import {
  Brain, BookOpen, FileText, Calendar, Heart, BarChart2,
  Target, Mic, Layers, HelpCircle, Zap, Briefcase,
  Newspaper, TrendingUp, Code2, Mail, LineChart, Bot,
  Bell, BookMarked, BellRing, Moon, Smartphone, Shield,
  Download, MessageSquare, Users, Trophy, Camera, Clock,
  UserPlus, Vote, CheckSquare, ExternalLink, Award
} from 'lucide-react'

const CATEGORIES = [
  {
    id: 'ai-learning', label: '🧠 AI Learning',
    accent: 'text-blue-400', border: 'border-blue-500/30',
    features: [
      { icon: Brain, title: 'AI Chatbot', desc: '24/7 Gemini-powered academic assistant', tag: 'Live' },
      { icon: FileText, title: 'Smart Summarizer', desc: 'Condense any study material instantly', tag: 'Live' },
      { icon: BookOpen, title: 'Notes Generator', desc: 'Structured markdown notes from text', tag: 'Live' },
      { icon: HelpCircle, title: 'Question Generator', desc: 'Auto-create practice questions', tag: 'Live' },
      { icon: Layers, title: 'Flashcard Generator', desc: 'AI Q&A decks with mastery tracking', tag: 'New' },
      { icon: Zap, title: 'Quiz Arena', desc: 'Timed MCQs auto-generated by AI', tag: 'New' },
      { icon: Brain, title: 'Mind Map Generator', desc: 'Visual concept maps from any topic', tag: 'New' },
      { icon: TrendingUp, title: 'Adaptive Learning', desc: 'Platform adjusts to your learning pace', tag: 'New' },
    ],
  },
  {
    id: 'career', label: '🚀 Career Tools',
    accent: 'text-emerald-400', border: 'border-emerald-500/30',
    features: [
      { icon: Target, title: 'Career Roadmap', desc: 'Step-by-step personalized career paths', tag: 'Live' },
      { icon: Briefcase, title: 'Skill Gap Analyzer', desc: 'Identify missing skills for your dream job', tag: 'New' },
      { icon: CheckSquare, title: 'AI Resume Builder', desc: 'Professional resume generated from profile', tag: 'New' },
      { icon: Mic, title: 'Mock Interview', desc: 'AI simulates real HR + technical interviews', tag: 'New' },
      { icon: ExternalLink, title: 'LinkedIn Optimizer', desc: 'Rewrite profile to attract recruiters', tag: 'New' },
      { icon: Newspaper, title: 'Live Job Board', desc: 'Real internships filtered by your goal', tag: 'New' },
      { icon: LineChart, title: 'Salary Insights', desc: 'Industry trends and growth analysis', tag: 'New' },
      { icon: Code2, title: 'Project Idea Gen', desc: 'Portfolio projects with tech stacks', tag: 'New' },
      { icon: Mail, title: 'Cover Letter Writer', desc: 'Personalized outreach emails in seconds', tag: 'New' },
    ],
  },
  {
    id: 'analytics', label: '📊 Analytics',
    accent: 'text-amber-400', border: 'border-amber-500/30',
    features: [
      { icon: BarChart2, title: 'Academic Tracker', desc: 'Grades and attendance with visual charts', tag: 'Live' },
      { icon: Heart, title: 'Wellbeing Check-in', desc: 'Stress, sleep, and focus AI analysis', tag: 'Live' },
      { icon: Calendar, title: 'AI Timetable', desc: 'Smart weekly schedule generator', tag: 'Live' },
      { icon: LineChart, title: 'Grade Forecasting', desc: 'Predict final exam scores with AI', tag: 'New' },
      { icon: Clock, title: 'Exam Countdown', desc: 'Reminders and study plan adjustments', tag: 'New' },
      { icon: Newspaper, title: 'Resource Aggregator', desc: 'Curated learning materials per topic', tag: 'New' },
    ],
  },
  {
    id: 'teacher', label: '👩‍🏫 Teacher',
    accent: 'text-pink-400', border: 'border-pink-500/30',
    features: [
      { icon: FileText, title: 'Question Paper Gen', desc: 'AI-generated exam papers instantly', tag: 'Live' },
      { icon: Users, title: 'Student Management', desc: 'View and manage enrolled students', tag: 'Live' },
      { icon: BookMarked, title: 'Playlist Manager', desc: 'YouTube-linked lecture organization', tag: 'Live' },
      { icon: BarChart2, title: 'Class Analytics', desc: 'Performance heatmaps and at-risk alerts', tag: 'New' },
      { icon: Bot, title: 'AI Assignment Grader', desc: 'Auto-grade submissions with feedback', tag: 'New' },
      { icon: Bell, title: 'Announcements', desc: 'Broadcast notices to all students', tag: 'New' },
      { icon: Vote, title: 'Live Poll & Quiz', desc: 'Real-time classroom engagement tool', tag: 'New' },
      { icon: BookMarked, title: 'Lesson Plan Gen', desc: 'Full lesson plans generated by AI', tag: 'New' },
    ],
  },
  {
    id: 'platform', label: '⚡ Platform',
    accent: 'text-violet-400', border: 'border-violet-500/30',
    features: [
      { icon: MessageSquare, title: 'Student-Teacher Chat', desc: 'In-app direct messaging system', tag: 'New' },
      { icon: CheckSquare, title: 'Assignment Submission', desc: 'Submit, grade, and track assignments', tag: 'New' },
      { icon: Trophy, title: 'Gamification', desc: 'XP, streaks, and classroom leaderboards', tag: 'New' },
      { icon: Camera, title: 'Image Doubt Solver', desc: 'Photo a question, AI solves it', tag: 'New' },
      { icon: BellRing, title: 'Smart Notifications', desc: 'Context-aware study alerts', tag: 'New' },
      { icon: Smartphone, title: 'PWA Install', desc: 'Works offline, installs like native app', tag: 'New' },
      { icon: Shield, title: 'Google OAuth', desc: 'One-click secure login', tag: 'New' },
      { icon: Download, title: 'Export Everything', desc: 'PDF, PNG, shareable links', tag: 'New' },
      { icon: UserPlus, title: 'Study Groups', desc: 'Peer rooms for collaborative learning', tag: 'New' },
      { icon: Moon, title: 'Themes', desc: 'Dark, light, and custom color schemes', tag: 'New' },
    ],
  },
]

const TAG_STYLES = {
  Live: 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/30',
  New: 'bg-blue-500/20 text-blue-300 border border-blue-500/30',
}

export default function Features() {
  const [activeTab, setActiveTab] = useState('ai-learning')
  const sectionRef = useRef(null)

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => entries.forEach(e => {
        if (e.isIntersecting) {
          e.target.querySelectorAll('.fade-up').forEach(el => el.classList.add('visible'))
        }
      }),
      { threshold: 0.05 }
    )
    if (sectionRef.current) observer.observe(sectionRef.current)
    return () => observer.disconnect()
  }, [activeTab])

  const activeCategory = CATEGORIES.find(c => c.id === activeTab)

  return (
    <section id="features" ref={sectionRef} className="relative py-24 overflow-hidden">
      <div className="absolute inset-0 bg-gradient-to-b from-transparent via-blue-950/10 to-transparent pointer-events-none" />
      <div className="max-w-7xl mx-auto px-6">
        <div className="text-center mb-14 fade-up">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full glass-card border border-blue-500/20 text-blue-400 text-xs font-medium mb-4">
            <Zap className="w-3.5 h-3.5" /> 32 Features — 5 Categories
          </div>
          <h2 className="font-syne font-extrabold text-4xl md:text-5xl text-white mb-4">
            Everything You Need to<br />
            <span className="gradient-text">Succeed Academically</span>
          </h2>
          <p className="text-slate-400 text-lg max-w-2xl mx-auto font-dm">
            From your first lecture to your first job offer — IntelliPath is with you at every step.
          </p>
        </div>

        <div className="fade-up delay-100 flex flex-wrap justify-center gap-2 mb-10">
          {CATEGORIES.map(cat => (
            <button key={cat.id} onClick={() => setActiveTab(cat.id)}
              className={`px-5 py-2.5 rounded-xl text-sm font-medium transition-all duration-300 ${
                activeTab === cat.id ? 'bg-blue-600 text-white shadow-lg shadow-blue-500/20' : 'glass-card text-slate-400 hover:text-white'
              }`}>
              {cat.label}
            </button>
          ))}
        </div>

        {activeCategory && (
          <div key={activeTab} className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
            {activeCategory.features.map((feat, i) => {
              const Icon = feat.icon
              return (
                <div key={feat.title} className={`fade-up delay-${(i % 5 + 1) * 100} glass-card-hover rounded-2xl p-5`}>
                  <div className="flex items-start justify-between mb-3">
                    <div className={`w-10 h-10 rounded-xl glass-card flex items-center justify-center ${activeCategory.border}`}>
                      <Icon className={`w-5 h-5 ${activeCategory.accent}`} />
                    </div>
                    <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${TAG_STYLES[feat.tag]}`}>
                      {feat.tag}
                    </span>
                  </div>
                  <h4 className="font-syne font-semibold text-sm text-white mb-1">{feat.title}</h4>
                  <p className="text-xs text-slate-400 leading-relaxed font-dm">{feat.desc}</p>
                </div>
              )
            })}
          </div>
        )}

        <div className="fade-up mt-12 text-center">
          <p className="text-slate-500 text-sm font-dm">
            <span className="text-blue-400 font-semibold">8 features already live</span> ·{' '}
            <span className="text-purple-400 font-semibold">24 new features</span> being built in React
          </p>
        </div>
      </div>
    </section>
  )
}